#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017/3/5 下午4:33
# @Author  : r00t
# @Site    : 
# @File    : portScan.py
# @Software: PyCharm


import socket
import sys
from datetime import datetime
from multiprocessing.dummy import Pool as ThreadPool

socket.setdefaulttimeout(0.5)
port = sys.argv[0]
hostFileName = sys.argv[1]

t1 = datetime.now()

hosts=[]
def readHost(hostFileName):
    fs = open(hostFileName,'r').readlines()
    for host in fs:
        hosts.append(int(host))


def useAge():
    print
    print "Useage:"
    print
    print "portScan.py Port hostFileName"
    print
    #print '_' * 60
    #print 'Please wait, scanning...'
    #print '_' * 60


def scan_port(port,host):
    try:
        s = socket.socket(2,1)
        res = s.connect_ex((host,port))
        if res == 0:
            print 'Port {}: OPEN'.format(port)
        s.close()
    except Exception,e:
        print str(e.message)




if __name__ == '__main__':
    if len(sys.argv) == 2:
        useAge()
        pool = ThreadPool(processes=10)
        results = pool.map(scan_port,hosts)
        pool.close()
        pool.join()
        t2 = datetime.now() -t1
        print t2
